### ISSUE TITLE
Upgrade ecto to 3.0.7

### ISSUE THREAD

**Issue by vasuadari** [ZennerIoT/ex_audit#11]

**Comment by lulu-2021** [comment]
Please update to latest version of Ecto

**Comment by narrowtux** [comment]
Work is ongoing in #9

**Comment by vasuadari** [comment]
@narrowtux Should i close this issue to avoid the confusion?

**Comment by narrowtux** [comment]
Since there's a link to the PR I think we leave this open

**Comment by vasuadari** [comment]
> Please update to latest version of Ecto

@netflakes `3.0.7` is the latest.

**Comment by narrowtux** [comment]
Ecto 3.1 just came out and changed repo internals again, I'm fixing them in #13

**Comment by narrowtux** [comment]
`0.6.0` was shipped with ecto 3.1 support
