### ISSUE TITLE
(Postgrex.Error) ERROR 23502 (not_null_violation) null value in column "id" of relation "versions" violates not-null constraint

### ISSUE THREAD

**Issue by mackdunkan** [ZennerIoT/ex_audit#111]
[debug] QUERY OK source="orders" db=0.6ms
UPDATE "orders" SET "status" = $1, "updated_at" = $2 WHERE "id" = $3 [:active, ~N[2024-02-08 11:55:30], "f1b82004-7560-40d6-b98f-3909319a15da"]
↳ Logistic.Orders.update_order/2, at: lib/logistic/orders.ex:78
[debug] QUERY ERROR source="versions" db=0.6ms
INSERT INTO "versions" ("action","patch","recorded_at","entity_id","entity_schema") VALUES ($1,$2,$3,$4,$5) [:updated, %{status: {:changed, {:primitive_change, :delivered, :active}}, updated_at: {:changed, %{second: {:changed, {:primitive_change, 23, 30}}, day: {:changed, {:primitive_change, 6, 8}}, minute: {:changed, {:primitive_change, 58, 55}}, hour: {:changed, {:primitive_change, 14, 11}}}}}, ~U[2024-02-08 11:55:30Z], "f1b82004-7560-40d6-b98f-3909319a15da", Logistic.Orders.Order]
↳ ExAudit.Schema.augment_transaction/3, at: lib/repo/schema.ex:146
[debug] QUERY OK db=0.3ms
rollback []
↳ ExAudit.Schema.augment_transaction/3, at: lib/repo/schema.ex:146
[error] GenServer #PID<0.9328.0> terminating
** (Postgrex.Error) ERROR 23502 (not_null_violation) null value in column "id" of relation "versions" violates not-null constraint

    table: versions
    column: id

Failing row contains (null, \x8374000000027706737461747573680277076368616e676564680377107072..., f1b82004-7560-40d6-b98f-3909319a15da, orders, updated, 2024-02-08 11:55:30, f, null, null, null, null, null).
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:925: Ecto.Adapters.SQL.insert_all/9
    (ecto 3.11.1) lib/ecto/repo/schema.ex:59: Ecto.Repo.Schema.do_insert_all/7
    (ex_audit 0.10.0) lib/repo/schema.ex:34: anonymous fn/5 in ExAudit.Schema.update/4
    (ex_audit 0.10.0) lib/repo/schema.ex:155: ExAudit.Schema.run_in_multi/4
    (ecto 3.11.1) lib/ecto/multi.ex:883: Ecto.Multi.apply_operation/5
    (elixir 1.16.0) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.11.1) lib/ecto/multi.ex:856: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1358: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.6.0) lib/db_connection.ex:1710: DBConnection.run_transaction/4
    (ecto 3.11.1) lib/ecto/repo/transaction.ex:18: Ecto.Repo.Transaction.transaction/4
    (ex_audit 0.10.0) lib/repo/schema.ex:146: ExAudit.Schema.augment_transaction/3
    (logistic 0.1.0) lib/logistic/orders.ex:78: Logistic.Orders.update_order/2
    (logistic 0.1.0) lib/logistic_web/live/dashboard_operator/order_live/form_component.ex:180: LogisticWeb.DashboardOperator.OrderLive.FormComponent.handle_event/3
    (phoenix_live_view 0.20.2) lib/phoenix_live_view/channel.ex:716: anonymous fn/4 in Phoenix.LiveView.Channel.inner_component_handle_event/4
    
    (phoenix_live_view 0.20.2) lib/phoenix_live_view/diff.ex:211: Phoenix.LiveView.Diff.write_component/4
    (phoenix_live_view 0.20.2) lib/phoenix_live_view/channel.ex:639: Phoenix.LiveView.Channel.component_handle_event/6
    (stdlib 5.2) gen_server.erl:1095: :gen_server.try_handle_info/3
    (stdlib 5.2) gen_server.erl:1183: :gen_server.handle_msg/6
    
config :logistic, Logistic.Repo, migration_primary_key: [name: :id, type: :uuid]
defmodule Logistic.Schema do
  @moduledoc false
  defmacro __using__(_) do
    quote do
      use Ecto.Schema
      @primary_key {:id, Ecto.UUID, autogenerate: true}
      @foreign_key_type Ecto.UUID
    end
  end
end

**Comment by narrowtux** [comment]
How does your version module look like? Does it include `@primary_key {:id, Ecto.UUID, autogenerate: true}` as well?

**Comment by mackdunkan** [comment]
yes includes

defmodule Logistic.Version do
  use Ecto.Schema
  use Logistic.Schema
  import Ecto.Changeset


  schema "versions" do

    # The patch in Erlang External Term Format
    field :patch, ExAudit.Type.Patch

    # supports UUID and other types as well
    field :entity_id, Ecto.UUID

    # name of the table the entity is in
    field :entity_schema, ExAudit.Type.Schema

    # type of the action that has happened to the entity (created, updated, deleted)
    field :action, ExAudit.Type.Action

    # when has this happened
    field :recorded_at, :utc_datetime

    # was this change part of a rollback?
    field :rollback, :boolean, default: false

    # custom fields
    belongs_to(:admin, Logistic.Admin.Accounts.Admin)
    belongs_to(:client, Logistic.Client.Accounts.Client)
    belongs_to(:operator, Logistic.Operator.Accounts.Operator)

    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:patch, :entity_id, :entity_schema, :action, :recorded_at, :rollback])
    |> cast(params, [:client_id, :operator_id, :admin_id]) # custom fields
  end
end

**Comment by narrowtux** [comment]
I don't see it TBH. Paste `@primary_key {:id, Ecto.UUID, autogenerate: true}` above `schema "versions" do`.

**Comment by mackdunkan** [comment]
use Logistic.Schema


defmodule Logistic.Schema do
  @moduledoc false
  defmacro __using__(_) do
    quote do
      use Ecto.Schema
      @primary_key {:id, Ecto.UUID, autogenerate: true}
      @foreign_key_type Ecto.UUID
    end
  end
end

**Comment by narrowtux** [comment]
That's another schema. Without `@primary_key` in `Logistic.Version` you will not be able to use ex_audit with UUID primary keys.

**Comment by mackdunkan** [comment]
thanks it works
