### ISSUE TITLE
But does not write to the database ex_audit_custom

### ISSUE THREAD

**Issue by mackdunkan** [ZennerIoT/ex_audit#112]
def insert_versions(module, changes, opts)

> [
  %{
    action: :updated,
    patch: %{
      status: {:changed, {:primitive_change, :active, :delivered}},
      updated_at: {:changed,
       %{
         second: {:changed, {:primitive_change, 34, 58}},
         minute: {:changed, {:primitive_change, 10, 19}}
       }}
    },
    entity_id: "f1b82004-7560-40d6-b98f-3909319a15da",
    entity_schema: Logistic.Orders.Order
  }
]
Logistic.Repo
[
  ex_audit_custom: [operator_id: "2840b6a9-3386-414d-bc90-1151154ab575"],
  stacktrace: [
    {Ecto.Repo.Supervisor, :tuplet, 2,
     [file: ~c"lib/ecto/repo/supervisor.ex", line: 163]},
    {Logistic.Repo, :update, 2,
     [file: ~c"deps/ex_audit/lib/repo/repo.ex", line: 119]},
    {Logistic.Orders, :update_order, 2,
     [file: ~c"lib/logistic/orders.ex", line: 78]},
    {LogisticWeb.DashboardOperator.OrderLive.FormComponent, :handle_event, 3,
     [
       file: ~c"lib/logistic_web/live/dashboard_operator/order_live/form_component.ex",
       line: 180
     ]},
    {Phoenix.LiveView.Channel, :"-inner_component_handle_event/4-fun-0-", 4,
     [file: ~c"lib/phoenix_live_view/channel.ex", line: 716]},
    {:telemetry, :span, 3,
     [
       file: ~c"/logistic/deps/telemetry/src/telemetry.erl",
       line: 321
     ]},
    {Phoenix.LiveView.Diff, :write_component, 4,
     [file: ~c"lib/phoenix_live_view/diff.ex", line: 211]},
    {Phoenix.LiveView.Channel, :component_handle_event, 6,
     [file: ~c"lib/phoenix_live_view/channel.ex", line: 639]},
    {:gen_server, :try_handle_info, 3, [file: ~c"gen_server.erl", line: 1095]},
    {:gen_server, :handle_msg, 6, [file: ~c"gen_server.erl", line: 1183]},
    {:proc_lib, :wake_up, 3, [file: ~c"proc_lib.erl", line: 251]}
  ]
]

[debug] QUERY OK source="versions" db=3.3ms
INSERT INTO "versions" ("action","patch","recorded_at","entity_id","entity_schema") VALUES ($1,$2,$3,$4,$5) [:updated, %{status: {:changed, {:primitive_change, :active, :delivered}}, updated_at: {:changed, %{second: {:changed, {:primitive_change, 34, 58}}, minute: {:changed, {:primitive_change, 10, 19}}}}}, ~U[2024-02-09 11:19:58Z], "f1b82004-7560-40d6-b98f-3909319a15da", Logistic.Orders.Order]

ex_audit_custom: [operator_id: "2840b6a9-3386-414d-bc90-1151154ab575"], --- OK

But does not write to the database

`version_schema()
          |> apply(:changeset, [empty_version_schema, change])
          |> Map.get(:changes)`
		
#Ecto.Changeset<
  action: nil,
  changes: %{
    action: :updated,
    patch: %{
      status: {:changed, {:primitive_change, :active, :win}},
      updated_at: {:changed,
       %{
         second: {:changed, {:primitive_change, 22, 9}},
         minute: {:changed, {:primitive_change, 0, 6}}
       }}
    },
    recorded_at: ~U[2024-02-09 12:06:09Z],
    entity_id: "ff7908c4-118f-4c04-acf5-1712b0a2f4d9",
    entity_schema: Logistic.Orders.Order
  },
  errors: [operator_id: {"is invalid", [type: :id, validation: :cast]}],
  data: #Logistic.Version<>,
  valid?: false
>

**Comment by narrowtux** [comment]
hey Alexander, in the future, please work on your issue formatting. It's very hard to read the snippets of code that are just pasted into the issue description. You can use triple-backticks to create code blocks.

https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
