### ISSUE TITLE
Upserts support

### ISSUE THREAD

**Issue by aerosol** [ZennerIoT/ex_audit#18]
Options such as `on_conflict`, `conflict_target` and `returning` for upserts are passed down to `insert_versions` and cause a crash since the target is non existent for the `Version` schema.

```elixir
defmodule ExAudit.Test.Repo.Migrations.UniqueConstraint do
  use Ecto.Migration

  def change do
    alter table(:users) do
      add(:unique_field, :string)
    end

    create(unique_index(:users, [:unique_field]))
  end
end
```

```elixir
test "on conflict" do
    user = Repo.insert!(%User{name: "Admin", email: "admin@example.com", unique_field: "foo"})
    user2 = %User{name: "Should not change", email: "shouldchange@example.com", unique_field: "foo"}
    # this will crash
    Repo.insert!(user2, on_conflict: {:replace, [:email]}, conflict_target: :unique_field, returning: true)
end
```

I think it'd require dropping specific opts in `insert_versions` and introducing a new action type. I haven't figured out yet how to qualify upsert as either `update` or `insert` -- the most tricky bit is calculating diffs to support the rollback feature.

**Comment by chatamov** [comment]
I think the opts sent to Query should be separated from the new opts being added

**Comment by chatamov** [comment]
All requests with on_conflict fails

**Comment by narrowtux** [comment]
Oh yeah that's not right, I should implement a whitelist for the options passed to the version recording

**Comment by chatamov** [comment]
👍

**Comment by chatamov** [comment]
let me know when done, thank you!!

**Comment by chatamov** [comment]
@narrowtux  is there any update?

**Comment by narrowtux** [comment]
Sorry, I'm very swamped at work

**Comment by narrowtux** [comment]
@bruteforcecat fixed this. 

Update to 0.7
