### ISSUE TITLE
Support for insert_all

### ISSUE THREAD

**Issue by ashneyderman** [ZennerIoT/ex_audit#19]
insert_all does not seem to be supported. The relevant code in `ExAudit.Schema` module looks like a WIP ?

```
defmodule ExAudit.Schema do
  def insert_all(module, adapter, schema_or_source, entries, opts) do
    # TODO!
    opts = augment_opts(opts)
    Ecto.Repo.Schema.insert_all(module, adapter, schema_or_source, entries, opts)
  end

  ...

end
```

**Comment by rauann** [comment]
https://github.com/ZennerIoT/ex_audit/pull/63

**Comment by ludwikbukowski** [comment]
hey whats the status of this ?

**Comment by narrowtux** [comment]
I've closed the PR, see the reason why: https://github.com/ZennerIoT/ex_audit/pull/63#issuecomment-1240690171
