### ISSUE TITLE
Application get_env when using as a library

### ISSUE THREAD

**Issue by simonprev** [ZennerIoT/ex_audit#2]
Hi, the lib doesn’t seem to pickup the config when calling `Application.get_env(:ex_audit, :tracked_schemas)`. If I call it in my app, I get a List. But in the lib it gets `nil`. Could this be an error in the order of compilation?

The blog post seems to talk about the problems in configuring a lib the way `ex_audit` does: https://michal.muskala.eu/2017/07/30/configuring-elixir-libraries.html

Or maybe I misconfigured something, 😄 

Thanks!

**Comment by narrowtux** [comment]
Runtime configuration is of no use for this key, so I'm using the normal Application config there. Can you tell me a bit more about your setup:

 * Elixir/Erlang version
 * mix.exs file
 * config.exs file

If setup correctly, the application configuration should work fine.

**Comment by simonprev** [comment]
Sorry for the delay, I tried it again but a cleaned the build/deps first and everything was working perfectly 👍 

Thanks for the great lib 😄
