### ISSUE TITLE
Compilation error with Ecto 3.1.2 and higher

### ISSUE THREAD

**Issue by torasakura** [ZennerIoT/ex_audit#20]
I'm getting a compilation error when i use ex_audit with ecto 3.1.2 or higher. 

```
== Compilation error in file example/repo.ex ==
** (MatchError) no match of right hand side value: {:ex_audit, Ecto.Adapters.Postgres, ExAudit.Test.Repo, [Ecto.Adapter, Ecto.Adapter.Migration, Ecto.Adapter.Queryable, Ecto.Adapter.Schema, Ecto.Adapter.Transaction, Ecto.Adapter.Storage, Ecto.Adapter.Structure]}
    example/repo.ex:2: (module)
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
```
With ecto 3.1.1 everything seems fine.

To reproduce it:
- clone this repo
- pin ecto to at least 3.1.2
- run `mix deps.get`
- run tests

**Comment by freandre** [comment]
hi ! 
I've noticed this behavior also on 3.1.5,  currently using 3.1.4 to avoid this problem.

**Comment by narrowtux** [comment]
Upgrade to ecto 3.2 and ex_audit 0.7
