### ISSUE TITLE
Error when upgrading to ecto_sql 3.2

### ISSUE THREAD

**Issue by jonatandahora** [ZennerIoT/ex_audit#21]
I'm getting this error when using version 3.2 of ecto_sql:

`** (UndefinedFunctionError) function NeopagSchema.Repo.prepare_query/3 is undefined or private, but the behaviour Ecto.Repo expects it to be present
    (neopag_schema) NeopagSchema.Repo.prepare_query(:all, #Ecto.Query<from c0 in NeopagSchema.Store.ChargingSetting, select: c0>, [])
    (ecto) lib/ecto/repo/queryable.ex:159: Ecto.Repo.Queryable.execute/4
    (ecto) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3`

I've tried to redefine the `prepare_query` function in the module `ExAudit.Repo` with no success.

**Comment by youalreadydid** [comment]
Hi, #26 aims to support Ecto 3.2. It would be nice if you can test it with your projects :)

**Comment by narrowtux** [comment]
I just merged #26 and published v 0.7. Thanks again @youalreadydid
