### ISSUE TITLE
support for different Version schemf for multi repo.

### ISSUE THREAD

**Issue by kafaichoi** [ZennerIoT/ex_audit#23]
with the way current config loading, it looks like there is no way to use ex_audit for different Version schema for multiple Ecto.Repo?

Will it be something that we will consider adding support for `ex_audit`?

I started a branch from my fork(https://github.com/AltoFinancial/ex_audit/tree/kafai--support-multi-repos). Please let me know your opinion on it. (Sorry for the code quality. I was rushing and I will further improve it if it's what we think should add for this library)

**Comment by narrowtux** [comment]
I think that's a great idea thanks.

The code itself looks fine :)

**Comment by kafaichoi** [comment]
that's great. I will work on it in the coming weekend and make a PR
