### ISSUE TITLE
Handling Decimal changes

### ISSUE THREAD

**Issue by yukster** [ZennerIoT/ex_audit#37]
This is part observation, part feature request, part wondering if I'm missing something. ExAudit was easy to set up and works great, however we store dollar amounts as Decimals. Since these are represented as structs with :coef, :sign, and :exp keys, ExAudit only records what changed in the struct. For example: `total: {:changed, %{coef: {:changed, {:primitive_change, 401, 153400}}}}`.

I've struggled to figure out how to use that data when printing out a change summary. Even if I look at two consecutive Version records, I don't have enough data to represent a Decimal. I'd have to start with the initial :added struct and apply each Version's change to it and show the use the last two revisions to show the old and new Decimal value. 

Instead, I am adding a custom field to my Version and I am storing all the before/after Decimals in a map in there. This also has its frustrations however, as I have a main record (purchase order) as well as a has_many (order items) that get recorded at the same time. I don't see a way to tell `ExAudit.track` which Version record to put the custom data on. I have it recording the field on the main record, but it seems I have to record all the custom data in that Version, rather than being able to put the order items' decimal changes in its Version record.

I can make this work in a pinch but was curious if there's some other approach I'm missing. Also, it seems like it would be useful to be able to record certain types, like decimals, as full struct diffs or before and after structs.

**Comment by yukster** [comment]
Oh, and another idea/problem with associations: it would be really sweet if you could access the version records for an association that map to a given version of the parent record. Like, for example, taking a purchase order Version and getting the order item Version records that apply at that PO version.

**Comment by yukster** [comment]
Figured out a big problem with my idea of tracking the decimal changes in some custom data that I pass through `ExAudit.track`: apparently you can only call that once in a transaction. I had `ExAudit.track(actor_id: conn.assigns.user.id)` in a plug, but when I call `ExAudit.track(custom_data: data)` further along in the request, it records custom_data and not actor. It would be nice if repeat calls merged the keyword lists and only cleared it after the txn commits. Maybe I can whip up a PR for that at some point.

**Comment by yukster** [comment]
I wound up forking and had it not breaking up Decimal structs pretty quickly: https://github.com/yukster/ex_audit/commit/b38f4fe4fdb9d13005a64b2e62d896d9489d326a

Happy to clean it up (my formatter made a lot of automatic changes) and make a PR if there's interest. I don't know if people want the added dependency of Decimal (which really should just be merged into the standard library). Another thought I had was to add a config for structs that should be considered primitives.

**Comment by narrowtux** [comment]
#46 should be enough to close this right?

**Comment by yukster** [comment]
Yep! Thanks!
