### ISSUE TITLE
Getting some errors on existing code

### ISSUE THREAD

**Issue by tiagodavi-papa** [ZennerIoT/ex_audit#54]
Hi Guys. I setup ExAudit and it seems is running fine, but some modules stopped working after replacing the original Repo by ExAudit. 

For example. Aggregations are not working anymore. 

`assert MyApp.Repo.aggregate(MyApp.SessionEvent, :count, :id) == 0`
` ** (UndefinedFunctionError) function nil.id/0 is undefined`

I am using Ecto "3.4.5" and I had to setup override: true to be compatible with ExAudit, but I think there's something wrong. 

Does anyone can help me understand this?

**Comment by narrowtux** [comment]
Should be fixed with the next release which you can preview with `{:ex_audit, github: "ZennerIoT/ex_audit"}` instead of passing a version number
