### ISSUE TITLE
Tracking deletion of nested association in parent model update

### ISSUE THREAD

**Issue by leandro** [ZennerIoT/ex_audit#55]
Lets say that I have an `Article` entity with a `has_many :comments` in its schema. Imagine that I'm going through a comments listings in my UI and pick one of them to be deleted but also the UI allows me to update other attributes of the `Article` entity altogether. When I hit the submit button to actually update the entire article entity and its nested associations, will the current implementation detect the missing comment and include the comment deletion in the versions that will be inserted from this update operation? This question also applies to `has_one` associations too.

Is this kind of logic currently supported? I went over the source code, but apparently I didn't spot the logic that would handle that kind of scenario.

(Sorry to bring this doubt as an issue, but I didn't find a better way to make sure about the existence of this feature)

**Comment by narrowtux** [comment]
Ecto should call Repo.delete in this case. Can't say for sure though.
