### ISSUE TITLE
Restricting tracked_schemas makes versions unloadable

### ISSUE THREAD

**Issue by schnittchen** [ZennerIoT/ex_audit#58]
Trying to load such a version results in the error

```
cannot load `"no_longer_tracked_schema"` as type ExAudit.Type.Schema for field :entity_schema in ...
```

The reason is that the old schema is no longer returned here https://github.com/ZennerIoT/ex_audit/blob/master/lib/repo/schema_type.ex#L18

**Comment by narrowtux** [comment]
Hi! I'm sorry you're having an issue with loading old versions. 

Can you provide more details about your issue:

 * which function are you calling and how?
 * (if applicable) how did you configure ex_audit?
 * add the entire error message

**Comment by schnittchen** [comment]
I'm just calling `MyApp.Version |> MyApp.Repo.all` and the error I get is

```
cannot load `"some_table_name"` as type ExAudit.Type.Schema for field :entity_schema in %MyApp.Version{...}
```
(obviously with some real table name)

The error is easy to reproduce:

* have something tracked
* clear the `tracked_schemas` config
* run the query

Aside, the `version_schema` and `tracked_schemas` should not be configuration for the ex_audit application but somehow bound to the Repo at hand (see https://hexdocs.pm/elixir/1.9.1/library-guidelines.html#avoid-application-configuration)

**Comment by narrowtux** [comment]
I feel like this might be out of spec for this library. If you remove a schema from the config, you should also write a migration that deletes all of these entries (the `execute` function can be used in ecto migrations to run arbitrary SQL queries):

```sql
DELETE FROM versions WHERE entity_schema= 'some_table_name'
```

Of course, you could also decide to keep these in a seperate table before deleting them from the versions table: 

```sql
CREATE TABLE some_table_name_versions AS (SELECT * FROM versions WHERE entity_schema = 'some_table_name');
```

**Comment by schnittchen** [comment]
I just ran into this issue again after renaming a table. I had to go down to SQL to fix this, because the `ExAudit.Type.Schema` won't let me just add an arbitrary atom into the `:tracked_schemas` env.
