### ISSUE TITLE
Support for Repo.insert_or_update

### ISSUE THREAD

**Issue by jvoegele** [ZennerIoT/ex_audit#6]
I am experimenting with `ExAudit` for an application that makes heavy use of the `Repo.insert_or_update` function. Unfortunately, `ExAudit` does not currently capture and record the resulting insert or update operation.

I have verified that `Repo.insert` and `Repo.update` operations are both properly recorded in the `versions` table.

**Comment by narrowtux** [comment]
Closed by #7

**Comment by narrowtux** [comment]
should be contained in 0.4.2
