### ISSUE TITLE
Recording custom data with Plug does not work in Phoenix LiveView App

### ISSUE THREAD

**Issue by MMore** [ZennerIoT/ex_audit#68]
Hello,

thanks a lot for your library!

I've started using it in a Phoenix Live App. Everything works, except recording custom data like an `actor_id` using a Plug. I've added a Plug as described in the README. Then I've integrated it into a pipeline in my router. The Plug is definitely executed with the right information. 
Non-LiveView controller actions include the custom data. But LiveView actions not. Probably because of the websocket. Any idea how to adapt that for LiveView? Thank a lot!

**Comment by narrowtux** [comment]
LiveViews run in a separate process from the plug conn, so you have to call `ExAudit.track` in `mount/3` or whereever too.
