### ISSUE TITLE
Conflicting behaviors using ExAudit.Repo

### ISSUE THREAD

**Issue by spenavajr** [ZennerIoT/ex_audit#90]
Using ExAudit.Repo properly after usage of Ecto.Repo:
```
defmodule PINWaste.Repo do
  use Ecto.Repo,
    otp_app: :pin_waste,
    adapter: Ecto.Adapters.Postgres

  use ExAudit.Repo
```

This causes the following warning:
_warning: conflicting behaviours found. function default_options/1 is required by Ecto.Repo and ExAudit.Repo_

**Comment by spenavajr** [comment]
@narrowtux any clue here? figured tagging somebody would increase visibility on this.

**Comment by revati** [comment]
This is beacue Ecto.Repo it self requires such callback as well.

fix is in PR (just created): https://github.com/ZennerIoT/ex_audit/pull/92/commits/d229bc6a59db351676e00c678c3a99ed6896a40b

**Comment by ambuznego** [comment]
@revati 🙏 any update on getting that PR in? I am seeing this warning as well.
